name: wallrio
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+3

environment:
  sdk: '>=2.18.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  change_app_package_name: ^1.1.0
  dio: ^5.1.1
  simple_gradient_text: ^1.2.4
  flutter_native_splash: ^2.2.19
  shimmer: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.4
  provider: ^6.0.5
  flutter_staggered_grid_view: ^0.6.2
  cached_network_image: ^3.2.3
  palette_generator: ^0.3.3+2
  flutter_cache_manager: ^3.3.0
  async_wallpaper: ^2.0.2
  android_path_provider: ^0.3.0
  fluttertoast: ^8.2.2
  url_launcher: ^6.1.11
  lottie: ^2.3.2
  animated_icon_button: ^1.0.2
  path_provider: ^2.0.15
  shared_preferences: ^2.1.1
  animations: ^2.0.7
  firebase_messaging: ^14.6.1
  firebase_core: ^2.13.0
  package_info_plus: ^4.0.1
  firebase_auth: ^4.6.1
  google_sign_in: ^6.1.2
  logger: ^1.3.0
  flutter_local_notifications: ^14.1.0
  firebase_crashlytics: ^3.3.1
  firebase_analytics: ^10.4.1
  firebase_app_check: ^0.1.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/lottie/

  fonts:
    - family: POCOTech
      fonts:
        - asset: font/POCOTech-cool-Light.otf
          weight: 300
        - asset: font/POCOTech-cool-Book.otf
          weight: 400
        - asset: font/POCOTech-cool-Regular.otf
          weight: 500
        - asset: font/POCOTech-cool-Medium.otf
          weight: 600
        - asset: font/POCOTech-cool-SemiBold.otf
          weight: 700
        - asset: font/POCOTech-cool-Bold.otf
          weight: 800
