// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIE2YwbVJAbHdpSVE8WXoAkq-qWSHiGJE',
    appId: '1:340316492418:web:a78c0a38b241ae9ae89a9b',
    messagingSenderId: '340316492418',
    projectId: 'wallrio-e551b',
    authDomain: 'wallrio-e551b.firebaseapp.com',
    storageBucket: 'wallrio-e551b.appspot.com',
    measurementId: 'G-M5WKSQC80Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_BlkOSFRCVL7aLbPOCfokD65SGdxfr6Y',
    appId: '1:340316492418:android:4e3c43cdba731752e89a9b',
    messagingSenderId: '340316492418',
    projectId: 'wallrio-e551b',
    storageBucket: 'wallrio-e551b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDESnKuihDPTL4kkZxZK7YyBqUU7se-TI',
    appId: '1:340316492418:ios:cb24e45d496e7be8e89a9b',
    messagingSenderId: '340316492418',
    projectId: 'wallrio-e551b',
    storageBucket: 'wallrio-e551b.appspot.com',
    androidClientId: '340316492418-ha4d9psbogodbb11e20aeune03ghf4sl.apps.googleusercontent.com',
    iosClientId: '340316492418-nnc7j4iul3o7nj74m35d7866amvmlm32.apps.googleusercontent.com',
    iosBundleId: 'com.example.wallrio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDESnKuihDPTL4kkZxZK7YyBqUU7se-TI',
    appId: '1:340316492418:ios:cb24e45d496e7be8e89a9b',
    messagingSenderId: '340316492418',
    projectId: 'wallrio-e551b',
    storageBucket: 'wallrio-e551b.appspot.com',
    androidClientId: '340316492418-ha4d9psbogodbb11e20aeune03ghf4sl.apps.googleusercontent.com',
    iosClientId: '340316492418-nnc7j4iul3o7nj74m35d7866amvmlm32.apps.googleusercontent.com',
    iosBundleId: 'com.example.wallrio',
  );
}
