name: Flutter Build Generate
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      - name: Export key.properties file
        run: echo keys exported | base64 --decode > android/key.properties

      - name: Build APK
        run: flutter build apk --split-per-abi
