name: Flutter Build Generate
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
            flutter-version: 3.10.2
            flutter-architecture: x64        

      - name: Export key.properties file
        run: |
            echo "$KEY_PROPERTIES_BASE64" | base64 --decode > android/key.properties
        env:
            KEY_PROPERTIES_BASE64: | 
                c3RvcmVQYXNzd29yZD1rZXkxMjM0NTYNCmtleVBhc3N3b3JkPWtleTEyMzQ1Ng0Ka2V5QWxpYXM9d2FsbHJpbw0Kc3RvcmVGaWxlPUU6XFxXYWxsUmlvXFxrZXlcXGNyZWF0ZWRLZXkuamtzDQo=

      - name: Build APK
        run: flutter build apk --split-per-abi
